### ISSUE TITLE
Allow quick access to filtered marker categories (enhancement)

### ISSUE THREAD

**Issue by bluenote73** [blish-hud/Pathing#69]
I really love the convenience of the marker category filtering. It makes so much sense to just show me categories that have something going on in the zone I'm in.

But, occasionally often enough to be a pain - and this usually happens because of subcategories that could be organized better - I would like to be able to dip into those filtered categories. And when I need to do it, going to settings isn't the most convenient. I'd love to be able to do a temporary quick toggle - ideally by clicking or right clicking the "categories are hidden" label, to *one time* show hidden. That way on the fly I can dip into those hidden categories. But it should go back to being hidden as soon as I exit the menus.

Thanks for your consideration! So grateful for all the labor savings Blish gives me. :)

**Comment by dlamkins** [comment]
Alright, this will be available in the next module release.  You can see it in action below.  👍

https://gfycat.com/creativelimphart

**Comment by bluenote73** [comment]
You are an absolute legend dude :) thank you

**Comment by dlamkins** [comment]
Happy to help!  I'm going to go ahead and close this issue now.  This feature is available in v0.17.3 which can now be found in the module repo.  🙂
