### ISSUE TITLE
No Paths or Markers Displayed on Mini Map or Fullscreen Map

### ISSUE THREAD

**Issue by Tyrahnny** [blish-hud/Pathing#72]
As of a few days ago (I can't remember exactly when, maybe Sunday?), I have lost visibility of all my marker parks on the mini map and the fullscreen map. I can still see the icons and trails in game. I have tested all the packs in TacO and they show correctly there, but not in Blish HUD. I have toggled the visibility on and off for the markers in the pathing module settings but it has no change to the map markers, other than hiding what I see in front of my character if I use the main disable markers hotkey.

**Comment by dlamkins** [comment]
The API is down (it was taken down to avoid spoilers during release of EoD) and we use offset data provided by the API to determine where to draw them on the mini-map.  The API maintainer with ANET is actively working to bring it up as we speak and once it is back up, a restart of Blish HUD will restore those icons on the minimap and fullscreen map.

**Comment by dlamkins** [comment]
Many endpoints are slowly coming back up as we speak.  You can track them here:
https://status.gw2efficiency.com/
