### ISSUE TITLE
Pathing: manually resetting activated markers

### ISSUE THREAD

**Issue by EukerionGW2** [blish-hud/Pathing#81]
Hi all,
First of all I'd like to thank you for that wonderful piece of software, well done developers!

I've been looking for an answer everywhere and couldn't find it, so I'll ask it here: for the "Pathing" module, with the Tekkit marker pack, as you know when pressing "F" (by default) next to some markers, they disappear to help the user remember which markers they've already visited. With TacO, doing this adds the marker to a file called "activationdata.xml", and one can delete the file contents in order for TacO to show these markers again. I'm trying to understand how to do that with Blish but I haven't found the "activationdata.xml" file or any equivalent in the "markers" folder.

Any suggestions on how to manually reset the activated markers with Blish?

Thanks in advance!
Cheers
- Eukerion

**Comment by dlamkins** [comment]
Just FYI, we added a new feature "Ghost markers" which can be enabled in the settings.  While enabled, hidden markers will be shown with reduced opacity allowing you to recover those markers by interacting with them again.

**Comment by EukerionGW2** [comment]
> Just FYI, we added a new feature "Ghost markers" which can be enabled in the settings. While enabled, hidden markers will be shown with reduced opacity allowing you to recover those markers by interacting with them again.

Thanks for the info ;)
