### ISSUE TITLE
Marker scaling on mini-map panel and full-map screen

### ISSUE THREAD

**Issue by Charybdis** [blish-hud/Pathing#87]
The markers appear to be offset  by a scaling factor on the mini- and full-screen map.

Steps to reproduce:
1) Loaded Tekkit All-In-One marker pack
2) Markers on 3-D world view are placed correctly
3) Drag the mini-map around
4) As the marker approaches the bottom right corner then it moves to the true position on map (scaling issue, rather than offset)
5) Open full map
6) Repeat map drag, noting the same scaling issue (centre of screen is correct).

This is for the mini-map in the lower right corner of the screen. When the mini-map is top-right then the true position is the top-right corner.

Screen size 1080p, screenshot includes most game graphic settings.

![pathing_scaling](https://user-images.githubusercontent.com/23155785/220087088-a380f95b-5e50-4ba0-8635-6f76c4016f23.jpg)

**Comment by dlamkins** [comment]
I'm afraid there are simply too many factors for us to implement support for non-synced UI scaling. At least for now it's not on our roadmap. 

You can set your in-game resolution to small and keep Blish HUD synced to the game's UI scale if necessary.

**Comment by Charybdis** [comment]
Well the info you gave about the UI scaling has actually helped me find the solution.

BlishHUD already includes a setting on the interface size and the pathing module automatically honours it - there's no need for a separate implementation.

I wasn't aware that it was there, so problem solved!

![image](https://user-images.githubusercontent.com/23155785/220156701-24739b9f-72c6-4d2d-95a2-ea02d2e97dd8.png)
