### ISSUE TITLE
Minimap and fullscreen map

### ISSUE THREAD

**Issue by DanyPNG** [blish-hud/Pathing#91]
In the last update my minimap and fullscreen map stop showing markers, i try restarting and unistalling and nothing happen.

**Comment by dlamkins** [comment]
This is unrelated to the updated. It's caused by the Guild wars 2 API being down. You will have to wait until sometime on Aug 24 for it to return. 

https://en-forum.guildwars2.com/topic/135277-guild-wars-2-api-disabled-from-august-18-24/

**Comment by adamk33n3r** [comment]
Just curious, what causes it to not show on the map if the API is down? Seems like it would be unrelated but obviously it's not.
