### ISSUE TITLE
(Tekkit's Guides) "Brand Stomped" not tracking correctly

### ISSUE THREAD

**Issue by SnaccHBG** [blish-hud/Pathing#94]
For me, it was showing some repaired ones as incomplete (basically marked on the mini map) whereas some incomplete ones weren't shown at all and I had to resort to the wiki. Plus the addon shows a different number in the description and category.
![Guild Wars 2 29-Sep-23 8_45_55 AM](https://github.com/blish-hud/Pathing/assets/65660396/3231a5ea-cdf9-4bd5-a5c5-f2780410c626)
![P_20230929_085017](https://github.com/blish-hud/Pathing/assets/65660396/34d8b060-bd0d-4c4e-a2f9-c6ddbb873235)

**Comment by dlamkins** [comment]
The module just does what the pack tells it to do, so you'll need to reach out to the marker pack's creator if you believe there to be an issue with the pack. 

In this case, it looks like Tekkit's pack.
